resources:
  containers:
  - container: u16
    image: python:3.10.16-slim

  - container: u18
    image: python:3.11.11-slim

  - container: u20
    image: python:3.12.8-slim

jobs:
- job: RunInContainer
  pool:
    name: Azure Pipelines
    # name: Default
    vmImage: 'ubuntu-latest'

  strategy:
    matrix:
      Python310:
        containerResource: u16
        python.version: '3.10'
      Python311:
        containerResource: u18
        python.version: '3.11'
      Python312:
        containerResource: u20
        python.version: '3.12'

  container: $[ variables['containerResource'] ]

  steps:
  - script: printenv
    
  - script: |
      python -m pip install --upgrade pip
      pip install -r requirements.txt
    displayName: 'Install dependencies'

  - displayName: 'Archive files'
    task: ArchiveFiles@2
    inputs:
      rootFolderOrFile: $(System.DefaultWorkingDirectory)
      includeRootFolder: false
      archiveType: tar
      archiveFile: $(Build.ArtifactStagingDirectory)/$(Build.BuildId)-$(python.version).zip
      replaceExistingArchive: true

  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)'
      ArtifactName: 'drop'
      publishLocation: 'Container'

  - displayName: 'pytest'
    script: |
      pip install pytest pytest-azurepipelines
      python -m pytest
